// Only run through run-design-checks.sh against its disposable seeded database.
const { chromium, expect: baseExpect } = require(process.env.PLAYWRIGHT_MODULE || 'playwright/test');
// Client reads may still be pending when navigation or dialog dismissal finishes.
const expect = baseExpect.configure({ timeout: 15000 });
const assert = require('node:assert/strict');
const { execFileSync } = require('node:child_process');
const base = process.env.HORAE_TEST_URL;
assert.ok(base, 'Set HORAE_TEST_URL to an isolated test instance');
const target = new URL(base);
const database = new URL(process.env.DATABASE_URL);
assert.ok(['localhost', '127.0.0.1'].includes(target.hostname) && target.port === '8093');
assert.equal(database.pathname, '/horae');
assert.ok(database.searchParams.get('host')?.startsWith('/tmp/horae-browser.'));
const sql = query => execFileSync('psql', [process.env.DATABASE_URL, '-X', '-v', 'ON_ERROR_STOP=1', '-qAt', '-c', query], { encoding: 'utf8' }).trim();

(async () => {
  const browser = await chromium.launch({ executablePath: process.env.CHROMIUM_PATH || undefined, headless: true });
  const page = await browser.newPage({ viewport: { width: 1440, height: 900 } });
  const errors = [];
  page.on('pageerror', error => errors.push(error.message));
  const name = `Clients browser ${Date.now()}`;
  const dialog = page.getByRole('dialog');
  const field = label => dialog.getByRole('textbox', { name: label, exact: true });
  try {
    await page.goto(`${base}/auth/login`);
    await page.getByRole('button', { name: 'Sign in as Admin', exact: true }).click();
    await page.waitForURL(`${base}/`);
    await page.goto(`${base}/clients`);
    const create = page.getByRole('button', { name: 'New client', exact: true }).first();
    await create.click();
    await expect(dialog).toBeVisible();
    await expect(field('Client name')).toBeFocused();
    await dialog.getByRole('button', { name: 'Create client', exact: true }).click();
    await expect(dialog.getByRole('alert')).toContainText('1–200 characters');
    await expect(dialog.getByRole('alert')).toBeFocused();
    await field('Client name').fill(name);
    const dirtyNavigation = page.waitForEvent('dialog');
    const navigation = page.evaluate(() => history.pushState(null, '', '/projects'));
    const warning = await dirtyNavigation;
    assert.equal(warning.message(), 'Discard unsaved client changes?');
    await warning.dismiss();
    await navigation;
    await expect(page).toHaveURL(`${base}/clients`);
    await expect(field('Client name')).toHaveValue(name);
    await field('Default rate').fill('0');
    await field('Billing address').fill('Test street\nFloor 2');
    await field('Tax ID (optional)').fill('TEST-VAT');
    await dialog.getByRole('combobox', { name: 'Currency', exact: true }).selectOption('EUR');
    await dialog.getByRole('button', { name: 'Create client', exact: true }).click();
    await expect(dialog).toBeHidden();
    await expect(create).toBeFocused();
    await page.getByRole('searchbox', { name: 'Search clients by name' }).fill(name);
    const link = page.getByRole('link', { name, exact: true });
    await expect(link).toHaveCount(1);
    const detailPath = await link.getAttribute('href');
    assert.match(detailPath, /^\/clients\/[0-9a-f-]+$/);
    await page.reload();
    await page.getByRole('link', { name, exact: true }).click();
    await expect(page.getByRole('heading', { name, exact: true })).toBeVisible();
    await expect(page.getByRole('region', { name: 'Billing', exact: true })).toContainText('EUR 0.00 / h');
    const edit = page.getByRole('button', { name: 'Edit client', exact: true });
    await edit.click();
    await expect(field('Default rate')).toHaveValue('0.00');
    await expect(field('Billing address')).toHaveValue('Test street\nFloor 2');
    await field('Billing address').fill('Must not be saved');
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click();
    await expect(dialog).toBeHidden();
    await expect(edit).toBeFocused();
    await page.reload();
    await expect(page.getByRole('region', { name: 'Billing', exact: true })).toContainText('Test street');
    await edit.click();
    await dialog.getByRole('combobox', { name: 'Currency', exact: true }).selectOption('USD');
    await dialog.getByRole('button', { name: 'Save changes', exact: true }).click();
    await expect(dialog.getByRole('alert')).toContainText('Confirm the default rate');
    await expect(field('Default rate')).toHaveValue('0.00');
    await dialog.getByRole('button', { name: 'Use this rate in USD', exact: true }).click();
    await dialog.getByRole('button', { name: 'Save changes', exact: true }).click();
    await expect(dialog).toBeHidden();
    await expect(page.getByRole('region', { name: 'Billing', exact: true })).toContainText('USD 0.00 / h');
    await page.reload();
    await expect(page.getByRole('region', { name: 'Billing', exact: true })).toContainText('USD 0.00 / h');
    console.log('PASS: clients create/reload/edit/cancel and explicit currency/rate intent');

    await page.goto(`${base}/clients`);
    await create.click();
    const uncertainName = `${name} uncertain`;
    await field('Client name').fill(uncertainName);
    let release;
    let requests = 0;
    const gate = new Promise(resolve => { release = resolve; });
    const route = url => url.pathname.includes('/api/create_client_profile');
    await page.route(route, async request => { requests++; await gate; await request.abort('failed'); });
    try {
      const sent = page.waitForRequest(request => request.url().includes('/api/create_client_profile'));
      await dialog.getByRole('button', { name: 'Create client', exact: true }).click();
      await sent;
      await expect(dialog.getByRole('button', { name: 'Saving…', exact: true })).toBeDisabled();
      await expect(dialog.getByRole('button', { name: 'Cancel', exact: true })).toBeDisabled();
      await dialog.locator('form').evaluate(form => form.requestSubmit());
      await page.keyboard.press('Escape');
      await page.mouse.click(4, 4);
      await expect(dialog).toBeVisible();
      assert.equal(requests, 1, 'pending submission is not duplicated');
      const pendingNavigation = page.waitForEvent('dialog');
      const navigation = page.evaluate(() => history.pushState(null, '', '/projects'));
      const warning = await pendingNavigation;
      assert.equal(warning.message(), 'A client save is pending. Wait for it to finish before leaving.');
      await warning.accept();
      await navigation;
      await expect(page).toHaveURL(`${base}/clients`);
      await expect(field('Client name')).toHaveValue(uncertainName);
    } finally { release(); }
    await expect(dialog.getByRole('status')).toContainText('Creation may have completed');
    await expect(field('Client name')).toHaveValue(uncertainName);
    await expect(dialog.getByRole('button', { name: 'Create client', exact: true })).toBeDisabled();
    await dialog.locator('form').evaluate(form => form.requestSubmit());
    assert.equal(requests, 1, 'uncertain creation is not automatically retried');
    const popupReady = page.waitForEvent('popup');
    await dialog.getByRole('link', { name: 'Check client list in a new tab', exact: true }).click();
    const popup = await popupReady;
    await expect(popup.getByRole('heading', { name: 'Clients', exact: true })).toBeVisible();
    await popup.close();
    await expect(field('Client name')).toHaveValue(uncertainName);
    await page.unroute(route);
    await dialog.getByRole('button', { name: 'I checked the list — allow another attempt', exact: true }).click();
    await dialog.getByRole('button', { name: 'Create client', exact: true }).click();
    await expect(dialog).toBeHidden();
    await page.getByRole('searchbox', { name: 'Search clients by name' }).fill(uncertainName);
    await expect(page.getByRole('link', { name: uncertainName, exact: true })).toHaveCount(1);
    console.log('PASS: pending guard and explicit uncertain-create recovery retain input');

    await create.click();
    const committedName = `${name} committed`;
    await field('Client name').fill(committedName);
    let committedRequests = 0;
    await page.route(route, async intercepted => {
      committedRequests++;
      const response = await intercepted.fetch();
      assert.ok(response.ok(), 'the server accepted creation before its response was lost');
      await intercepted.abort('failed');
    });
    await dialog.getByRole('button', { name: 'Create client', exact: true }).click();
    await expect(dialog.getByRole('status')).toContainText('Creation may have completed');
    await expect(field('Client name')).toHaveValue(committedName);
    const committedPopupReady = page.waitForEvent('popup');
    await dialog.getByRole('link', { name: 'Check client list in a new tab', exact: true }).click();
    const committedPopup = await committedPopupReady;
    await committedPopup.getByRole('searchbox', { name: 'Search clients by name' }).fill(committedName);
    await expect(committedPopup.getByRole('link', { name: committedName, exact: true })).toHaveCount(1);
    await committedPopup.close();
    await dialog.locator('form').evaluate(form => form.requestSubmit());
    await expect(dialog.getByRole('button', { name: 'Create client', exact: true })).toBeDisabled();
    assert.equal(committedRequests, 1, 'lost acknowledgement does not duplicate the committed client');
    await dialog.getByRole('button', { name: 'Cancel', exact: true }).click();
    await page.unroute(route);
    await page.reload();
    await page.getByRole('searchbox', { name: 'Search clients by name' }).fill(committedName);
    await expect(page.getByRole('link', { name: committedName, exact: true })).toHaveCount(1);
    console.log('PASS: lost creation acknowledgement can be inspected without duplicating or undoing the client');

    await page.getByRole('searchbox', { name: 'Search clients by name' }).fill('Acme Corp');
    await page.locator('#client-scope-menu-trigger').click();
    await page.getByRole('menuitem', { name: /^All clients/ }).click();
    const acme = page.getByRole('row').filter({ has: page.getByRole('link', { name: 'Acme Corp', exact: true }) });
    const projects = sql("SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY id), '[]') FROM projects p");
    const invoices = sql("SELECT coalesce(jsonb_agg(to_jsonb(i) ORDER BY id), '[]') FROM invoices i");
    await acme.getByRole('button', { name: 'Deactivate', exact: true }).click();
    await expect(acme.getByText('Inactive', { exact: true })).toBeVisible();
    assert.equal(sql("SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY id), '[]') FROM projects p"), projects);
    assert.equal(sql("SELECT coalesce(jsonb_agg(to_jsonb(i) ORDER BY id), '[]') FROM invoices i"), invoices);
    await acme.getByRole('button', { name: 'Activate', exact: true }).click();
    await expect(acme.getByText('Active', { exact: true })).toBeVisible();
    assert.equal(sql("SELECT coalesce(jsonb_agg(to_jsonb(p) ORDER BY id), '[]') FROM projects p"), projects);
    assert.equal(sql("SELECT coalesce(jsonb_agg(to_jsonb(i) ORDER BY id), '[]') FROM invoices i"), invoices);
    console.log('PASS: existing activation/deactivation does not cascade into projects or historical invoices');
    await page.getByRole('link', { name: 'Import', exact: true }).click();
    await expect(page).toHaveURL(`${base}/admin/importers`);
    await expect(page.getByRole('heading', { name: 'Importers', exact: true })).toBeVisible();
    console.log('PASS: the existing administrator import entry point remains reachable');
    assert.deepEqual(errors, [], 'no uncaught browser errors');
  } finally { await browser.close(); }
})().catch(error => { console.error(error); process.exit(1); });
