-- Durable application jobs. IDs are generated by Horae as UUID v7.
CREATE TABLE horae_jobs (
  id                uuid PRIMARY KEY,
  org_id            uuid NOT NULL REFERENCES organizations(id),
  kind              text NOT NULL,
  payload           jsonb NOT NULL,
  status            text NOT NULL DEFAULT 'queued'
                    CHECK (status IN ('queued', 'running', 'succeeded', 'failed', 'cancelled')),
  idempotency_key   text,
  attempts          integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  max_attempts     integer NOT NULL DEFAULT 5 CHECK (max_attempts > 0),
  available_at      timestamptz NOT NULL DEFAULT now(),
  lease_until       timestamptz,
  worker_id         text,
  phase             text,
  processed_count   bigint NOT NULL DEFAULT 0 CHECK (processed_count >= 0),
  total_count       bigint,
  checkpoint        jsonb,
  report            jsonb,
  last_error        text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  started_at        timestamptz,
  finished_at       timestamptz,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (org_id, kind, idempotency_key)
);

CREATE INDEX horae_jobs_claim_idx
  ON horae_jobs (available_at, created_at)
  WHERE status IN ('queued', 'running');

CREATE TABLE horae_job_uploads (
  job_id       uuid PRIMARY KEY REFERENCES horae_jobs(id) ON DELETE CASCADE,
  org_id       uuid NOT NULL REFERENCES organizations(id),
  filename     text NOT NULL,
  content_type text NOT NULL,
  body         bytea NOT NULL,
  created_at   timestamptz NOT NULL DEFAULT now(),
  CHECK (octet_length(body) <= 50 * 1024 * 1024)
);

CREATE TABLE horae_outbox (
  id             uuid PRIMARY KEY,
  org_id         uuid NOT NULL REFERENCES organizations(id),
  event_kind     text NOT NULL,
  payload        jsonb NOT NULL,
  attempts       integer NOT NULL DEFAULT 0 CHECK (attempts >= 0),
  available_at   timestamptz NOT NULL DEFAULT now(),
  delivered_at   timestamptz,
  last_error     text,
  created_at     timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX horae_outbox_delivery_idx
  ON horae_outbox (available_at, created_at)
  WHERE delivered_at IS NULL;
