//! Generates the utility stylesheet (`assets/css/horae-utils.css`) from the
//! design scale. The Node-free equivalent of a Tailwind build step.
//!
//! Token *values* live in `horae.css` `:root`; utilities only reference them via
//! `var(--…)`, so this file owns the class matrix, not the palette. Breakpoint
//! pixel values are literals because CSS custom properties cannot appear in
//! `@media` conditions — keep them in sync with the convention in DESIGN.md.

use std::fmt::Write as _;

/// Output path, relative to the crate root (`CARGO_MANIFEST_DIR`).
const OUT: &str = "assets/css/horae-utils.css";

/// Responsive breakpoints: `(prefix, min-width px)`. Must match DESIGN.md.
const BREAKPOINTS: &[(&str, u32)] = &[("sm", 640), ("md", 768), ("lg", 1024)];

fn main() {
    // Only re-run when the generator itself changes, not on every build.
    println!("cargo:rerun-if-changed=build.rs");

    let css = stylesheet();
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR").unwrap();
    let out_path = std::path::Path::new(&manifest_dir).join(OUT);

    // Compare against the existing file. If identical, skip the write to avoid
    // unnecessary rebuilds and to work in read-only environments (nix sandbox).
    if let Ok(existing) = std::fs::read_to_string(&out_path)
        && existing == css
    {
        return;
    }

    match std::fs::write(&out_path, &css) {
        Ok(()) => println!("cargo:warning=regenerated {OUT} ({} bytes)", css.len()),
        Err(e) => {
            // In a read-only sandbox the write fails. If the file existed but was
            // stale, that's a real problem — the committed file is out of date.
            panic!(
                "cannot write {}: {e}\n\
                 If this is a sandboxed build, regenerate locally:\n  \
                 cargo build -p horae && git add {OUT}",
                out_path.display()
            );
        }
    }
}

// ── CSS generation (ported from crates/cssgen) ──────────────────────────────

struct Family {
    title: &'static str,
    rules: Vec<(String, String)>,
}

fn stylesheet() -> String {
    let mut css = String::new();
    css.push_str(HEADER);
    for family in families() {
        let _ = writeln!(css, "\n/* {} */", family.title);
        for (class, decls) in family.rules {
            let _ = writeln!(css, ".{class} {{ {decls}; }}");
        }
    }
    css.push_str(&responsive());
    css
}

const HEADER: &str = "\
/* ────────────────────────────────────────────────────────────────────────
   GENERATED by build.rs — do not edit by hand.

   A Tailwind-style utility layer, but plain CSS backed by the design tokens in
   horae.css (`--space-*`, `--color-*`, …). The numeric spacing scale matches
   Tailwind's (`p-4` = --space-4 = 1rem). Compose utilities in markup; reach for
   a semantic component class (`.btn`, `.card`, `.badge`) for anything reused.
   ──────────────────────────────────────────────────────────────────────── */
";

fn space() -> Vec<(&'static str, String)> {
    let mut v = vec![("0", "0".to_string())];
    // Full scale — every step here must have a matching `--space-N` token in
    // horae.css `:root`, or the generated `var(--space-N)` resolves to nothing.
    for n in ["1", "2", "3", "4", "5", "6", "8", "10", "12", "16"] {
        v.push((n, format!("var(--space-{n})")));
    }
    v
}

fn families() -> Vec<Family> {
    vec![
        fixed(
            "Display",
            &[
                ("block", "display: block"),
                ("inline-block", "display: inline-block"),
                ("inline", "display: inline"),
                ("hidden", "display: none"),
                ("flex", "display: flex"),
                ("inline-flex", "display: inline-flex"),
                ("grid", "display: grid"),
            ],
        ),
        fixed(
            "Flexbox & grid",
            &[
                ("flex-col", "flex-direction: column"),
                ("flex-row", "flex-direction: row"),
                ("flex-wrap", "flex-wrap: wrap"),
                ("flex-1", "flex: 1"),
                ("flex-none", "flex: none"),
                ("items-start", "align-items: flex-start"),
                ("items-center", "align-items: center"),
                ("items-end", "align-items: flex-end"),
                ("items-baseline", "align-items: baseline"),
                ("justify-start", "justify-content: flex-start"),
                ("justify-center", "justify-content: center"),
                ("justify-end", "justify-content: flex-end"),
                ("justify-between", "justify-content: space-between"),
                (
                    "grid-cols-2",
                    "grid-template-columns: repeat(2, minmax(0, 1fr))",
                ),
                (
                    "grid-cols-3",
                    "grid-template-columns: repeat(3, minmax(0, 1fr))",
                ),
                (
                    "grid-cols-4",
                    "grid-template-columns: repeat(4, minmax(0, 1fr))",
                ),
                (
                    "grid-cols-5",
                    "grid-template-columns: repeat(5, minmax(0, 1fr))",
                ),
                (
                    "grid-cols-6",
                    "grid-template-columns: repeat(6, minmax(0, 1fr))",
                ),
                (
                    "grid-cols-7",
                    "grid-template-columns: repeat(7, minmax(0, 1fr))",
                ),
            ],
        ),
        spacing_family(),
        fixed(
            "Sizing",
            &[
                ("w-full", "width: 100%"),
                ("h-full", "height: 100%"),
                ("min-w-0", "min-width: 0"),
                ("max-w-sm", "max-width: 24rem"),
                ("max-w-md", "max-width: 28rem"),
                ("max-w-lg", "max-width: 32rem"),
            ],
        ),
        type_family(),
        fixed(
            "Text color",
            &[
                ("text-strong", "color: var(--color-text-strong)"),
                ("text-default", "color: var(--color-text)"),
                ("text-secondary", "color: var(--color-text-secondary)"),
                ("text-muted", "color: var(--color-text-secondary)"),
                ("text-faint", "color: var(--color-text-muted)"),
                ("text-label", "color: var(--color-label)"),
                ("text-primary", "color: var(--color-primary)"),
                ("text-accent", "color: var(--color-accent)"),
                ("text-success", "color: var(--color-success)"),
                ("text-danger", "color: var(--color-danger)"),
                ("text-warning", "color: var(--color-warning)"),
            ],
        ),
        fixed(
            "Background",
            &[
                ("bg-base", "background: var(--color-bg)"),
                ("bg-secondary", "background: var(--color-bg-secondary)"),
                ("bg-tertiary", "background: var(--color-bg-tertiary)"),
                ("bg-overlay", "background: var(--color-bg-overlay)"),
                ("bg-menu", "background: var(--color-menu)"),
                ("bg-primary", "background: var(--color-primary)"),
                ("bg-primary-soft", "background: var(--color-primary-bg)"),
            ],
        ),
        fixed(
            "Border & radius",
            &[
                ("border", "border: 1px solid var(--color-border)"),
                ("border-0", "border: none"),
                ("border-t", "border-top: 1px solid var(--color-border)"),
                ("border-b", "border-bottom: 1px solid var(--color-border)"),
                ("border-l", "border-left: 1px solid var(--color-border)"),
                ("border-r", "border-right: 1px solid var(--color-border)"),
                ("rounded-sm", "border-radius: var(--radius-sm)"),
                ("rounded", "border-radius: var(--radius)"),
                ("rounded-lg", "border-radius: var(--radius-lg)"),
                ("rounded-panel", "border-radius: var(--radius-panel)"),
                ("rounded-full", "border-radius: var(--radius-full)"),
            ],
        ),
        fixed(
            "Effects & position",
            &[
                ("shadow-sm", "box-shadow: var(--shadow-sm)"),
                ("shadow", "box-shadow: var(--shadow)"),
                ("shadow-md", "box-shadow: var(--shadow-md)"),
                ("shadow-menu", "box-shadow: var(--shadow-menu)"),
                ("shadow-modal", "box-shadow: var(--shadow-modal)"),
                ("relative", "position: relative"),
                ("absolute", "position: absolute"),
                ("overflow-hidden", "overflow: hidden"),
                ("overflow-x-auto", "overflow-x: auto"),
                ("cursor-pointer", "cursor: pointer"),
                ("opacity-60", "opacity: 0.6"),
            ],
        ),
    ]
}

fn spacing_family() -> Family {
    let mut rules = Vec::new();
    for (n, v) in space() {
        rules.push((format!("p-{n}"), format!("padding: {v}")));
        rules.push((
            format!("px-{n}"),
            format!("padding-left: {v}; padding-right: {v}"),
        ));
        rules.push((
            format!("py-{n}"),
            format!("padding-top: {v}; padding-bottom: {v}"),
        ));
        rules.push((format!("pt-{n}"), format!("padding-top: {v}")));
        rules.push((format!("pb-{n}"), format!("padding-bottom: {v}")));
        rules.push((format!("pl-{n}"), format!("padding-left: {v}")));
        rules.push((format!("pr-{n}"), format!("padding-right: {v}")));
        rules.push((format!("gap-{n}"), format!("gap: {v}")));
        rules.push((format!("m-{n}"), format!("margin: {v}")));
        rules.push((format!("mt-{n}"), format!("margin-top: {v}")));
        rules.push((format!("mb-{n}"), format!("margin-bottom: {v}")));
        rules.push((format!("ml-{n}"), format!("margin-left: {v}")));
        rules.push((format!("mr-{n}"), format!("margin-right: {v}")));
    }
    rules.push((
        "mx-auto".to_string(),
        "margin-left: auto; margin-right: auto".to_string(),
    ));
    rules.push(("ml-auto".to_string(), "margin-left: auto".to_string()));
    Family {
        title: "Spacing (padding / margin / gap)",
        rules,
    }
}

fn type_family() -> Family {
    let mut rules = Vec::new();
    for size in ["xs", "sm", "base", "lg", "xl", "2xl", "3xl", "display"] {
        rules.push((
            format!("text-{size}"),
            format!("font-size: var(--font-size-{size})"),
        ));
    }
    let fixed: &[(&str, &str)] = &[
        ("font-normal", "font-weight: 400"),
        ("font-medium", "font-weight: 500"),
        ("font-semibold", "font-weight: 600"),
        ("font-bold", "font-weight: 700"),
        ("text-left", "text-align: left"),
        ("text-center", "text-align: center"),
        ("text-right", "text-align: right"),
        ("uppercase", "text-transform: uppercase"),
        ("tracking-wide", "letter-spacing: 0.06em"),
        ("tracking-wider", "letter-spacing: 0.14em"),
        ("leading-tight", "line-height: 1.2"),
        ("font-sans", "font-family: var(--font-family)"),
        ("font-mono", "font-family: var(--font-family-mono)"),
        ("text-mono", "font-family: var(--font-family-mono)"),
        ("font-display", "font-family: var(--font-family-display)"),
        (
            "truncate",
            "overflow: hidden; text-overflow: ellipsis; white-space: nowrap",
        ),
        ("whitespace-nowrap", "white-space: nowrap"),
    ];
    for (c, d) in fixed {
        rules.push((c.to_string(), d.to_string()));
    }
    Family {
        title: "Typography",
        rules,
    }
}

const RESPONSIVE: &[(&str, &str)] = &[
    ("hidden", "display: none"),
    ("block", "display: block"),
    ("flex", "display: flex"),
    ("flex-row", "flex-direction: row"),
    ("flex-col", "flex-direction: column"),
    (
        "grid-cols-2",
        "grid-template-columns: repeat(2, minmax(0, 1fr))",
    ),
    (
        "grid-cols-3",
        "grid-template-columns: repeat(3, minmax(0, 1fr))",
    ),
    (
        "grid-cols-4",
        "grid-template-columns: repeat(4, minmax(0, 1fr))",
    ),
    ("text-right", "text-align: right"),
];

fn responsive() -> String {
    let mut css = String::from(
        "\n/* Responsive variants — `bp:util` (e.g. `md:flex-row`). Written plainly in\n   markup; the `:` is escaped only in the selector. */\n",
    );
    for (prefix, px) in BREAKPOINTS {
        let _ = writeln!(css, "@media (min-width: {px}px) {{");
        for (class, decls) in RESPONSIVE {
            let _ = writeln!(css, "  .{prefix}\\:{class} {{ {decls}; }}");
        }
        css.push_str("}\n");
    }
    css
}

fn fixed(title: &'static str, rules: &[(&str, &str)]) -> Family {
    Family {
        title,
        rules: rules
            .iter()
            .map(|(c, d)| (c.to_string(), d.to_string()))
            .collect(),
    }
}
